In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

z = np.dot(x, y)
print(z)

32


In [6]:
x = np.array([[0.0, 1.0], [2.0, 3.0], [4.0, 5.0]])
print(x.shape)
x = x.reshape((2, 3))
print(x)

(3, 2)
[[0. 1. 2.]
 [3. 4. 5.]]


In [4]:
x = np.zeros((300, 20))
x = np.transpose(x)

print(x.shape)

(20, 300)


In [4]:
x = tf.Variable(0.0)
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y, x)

In [2]:
x = tf.ones(shape=(2, 1))
print(x)

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


2023-03-11 11:45:31.618805: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-03-11 11:45:31.619293: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [3]:
x = tf.zeros(shape=(2, 1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [ ]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))