In [ ]:
# import necessary libraries

import tensorflow as tf

In [2]:
# create tensor with only 0 and 1

x = tf.ones(shape=(2, 1))
print(x)

x = tf.zeros(shape=(2, 1))
print(x)

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


2023-01-02 19:08:51.202511: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-01-02 19:08:51.202709: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [3]:
# create tensors with random values

x = tf.random.normal(shape=(3, 1), mean=0.0, stddev=1.0)
print(x)

tf.Tensor(
[[ 0.01271114]
 [-0.372031  ]
 [ 0.7423435 ]], shape=(3, 1), dtype=float32)


##### The line above is the same as:

```py
np.random.normal(size=(3, 1), loc=0., scale=1.)
```

##### in numpy


In [4]:
x = tf.random.uniform(shape=(3, 1), minval=0.0, maxval=1.0)
print(x)

tf.Tensor(
[[0.53363585]
 [0.5325005 ]
 [0.25014472]], shape=(3, 1), dtype=float32)


## NumPy vs TensorFlow:
TensorFlow's tensors are constant, which means they are immutable and vice versa for NumPy.